baseURL = "/"
languageCode = "en-us"
title = "康龙公卫"


description = "x-camp第一课作业"
tags = ["blog", "company"]
features = ["blog", "themes", "disqus"]
min_version = 0.29

[author]
    name = "shaolong98"
    homepage = "/"
